version: '3.4'

services:
  loplait:
    image: ${DOCKER_REGISTRY-}loplait
    build:
      context: .
      dockerfile: Loplait/Dockerfile
    ports:
      - "80:80" 
      - "443:443" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./app-data:/app/data 